### ISSUE TITLE
Switching between Vue 2 and Vue 3 to run tests with Composition API

### ISSUE THREAD

**Issue by dobromir-hristov** [vueuse/vue-demi#38]
## Summary

I tried using `vue-demi-switch 2 vue2` and defining `"vue2": "npm:vue@2"` in my package.json, but when I run tests, the `@vue/composition-api` breaks, because it imports Vue as `var Vue = require('vue');`

Do you have any advice on how to proceed with this? I saw `vueuse/core` uses this approach but I couldnt see if you have a fix for this.

You can see this in https://github.com/vuelidate/vuelidate/tree/next

**Comment by antfu** [comment]
@dobromir-hristov Sorry for the delay, what's the error message the plugin throws? You can run `install()` from `vue-demi` at the very beginning of your entry (setup file). It should feed the plugin with the right package.

**Comment by dobromir-hristov** [comment]
Its OK I got it working, in be it a hackier way :D https://github.com/vuelidate/vuelidate/blob/next/scripts/swap-vue.js

As I said the composition API imports vue from `vue` and aliasing as `vue2` did not do the job for some reason :/

**Comment by antfu** [comment]
Glad to know you get it to work. The plugin should only import Vue before installing, it should work for custom Vue instance (where vue demi feed it to) after the installations. 🤔

**Comment by renatodeleao** [comment]
Just had the same issue as @dobromir-hristov, but on my end was related to `@vue/test-utils`. 

I'm trying make a simple library isomorphic, and the default version is vue 2. I've aliased `"vue3": "npm:vue@3"` as documented on readme. On testing, I had to do the same for `"@vue/test-utils-vue3": "@npm:@vue/test-utils@^2.0.0"` and added some [`test-utils` middleware](https://github.com/vuelidate/vuelidate/blob/5013d34de15254473357d45ef540dfbe49517f0c/packages/vuelidate/test/unit/test-utils.js#L3) using `vue-demi` to require the appropriate testing package for the vue version. 

The problem was also that `@vue/test-utils` requires `var Vue = require('vue');` under the hood, which refers to vue 2  (the default). The `swap-vue.js` script from @dobromir-hristov saved the day, so this is a more of thank you **both** post, because I don't know how could `vue-demi` fix this issue.
