### ISSUE TITLE
Skypack version of vue-demi imports vue 2 but sets isVue3 to true

### ISSUE THREAD

**Issue by Demivan** [vueuse/vue-demi#72]
https://cdn.skypack.dev/-/vue-demi@v0.11.0-TmCmtDOAoOKuMLLEdJI0/dist=es2020,mode=imports/optimized/vue-demi.js

```js
export * from "/-/vue@v2.6.14-ZwqBV9vu181DzQDewEXR/dist=es2020,mode=imports/optimized/vue.js";
import * as vue from "/-/vue@v2.6.14-ZwqBV9vu181DzQDewEXR/dist=es2020,mode=imports/optimized/vue.js";
export {vue as Vue};
var isVue2 = false;
var isVue3 = true;
```

**Comment by antfu** [comment]
How could I fix that tho? 👀

**Comment by Demivan** [comment]
Actually I have no idea :smiley:. Not sure how Skypack decided to import `vue@2.6.14`
I just tried using my `fluent-vue` package with Skypack and got `ref is not defined`. Tracked it down to `vue-demi` importing wrong `vue` version.
Maybe changing order in peer dependencies from `"vue": "^2.6.0 || >=3.0.0"` to `"vue": "^3.0.0 || ^2.6.0"` will make Skypack load `vue@3`

**Comment by Demivan** [comment]
But I think no matter what you do Skypack version cannot be compatible with both `vue@2` and `vue@3`

**Comment by antfu** [comment]
> Maybe changing order in peer dependencies from "vue": "^2.6.0 || >=3.0.0" to "vue": "^3.0.0 || ^2.6.0" will make Skypack load vue@3

I don't mind trying :)

> But I think no matter what you do Skypack version cannot be compatible with both vue@2 and vue@3

Yeah, wondering why you need to use it with Skypack tho?

**Comment by Demivan** [comment]
> Yeah, wondering why you need to use it with Skypack tho?

I was just messing with it :) Wanted to try it out.  
So it is not a big deal if `vue-demi` is broken there. It shouldn't be a common use-case.

**Comment by Demivan** [comment]
v0.11.1 did not fix it. Going to close the issue. Will create pull request if I figure out how to make it work with Skypack.

**Comment by antfu** [comment]
The least thing we could do is to release 3 versions at the same time - `vue-demi@latest` `vue-demi@v2` `vue-demi@v3`. But not sure if it's worth it at the current stage.

**Comment by sibbng** [comment]
Since Skypack doesn't have any way to override package versions (query variables etc.) I would suggest using jspm and import maps. `vue-demi`'s functionality comes from it's post install hook which is where controls your vue version. In browser doing something like that possible with import maps.

I'm pretty sure you are not working on anything serious, and neither I do. That because I had experienced [@vueuse/core](https://vueuse.js.org/) + [reactivue](https://github.com/antfu/reactivue) previously to see how `vue-demi` works in browser. Here it is: https://focused-williams-cf307d.netlify.app/ You can do CTRL+U for source code. I linked vue to reactivue in this example but in your case you can simply link it to vue 3. For generating import maps https://generator.jspm.io/ could help.

> The least thing we could do is to release 3 versions at the same time - `vue-demi@latest` `vue-demi@v2` `vue-demi@v3`. But not sure if it's worth it at the current stage.

It will also require packages (fluent-vue, @vueuse/core etc) to release under 2 different tags. Since vue-demi isn't supposed to be used in that way it would be an unnecessary effort.
